### PR TITLE
Simpify php

### PR DESCRIPTION
**Pull request by nickschuch**
#### What does this PR do?

* Deletes php7.0 and php7.1 directories.
* Uses Makefile variable PHP_MINOR_VERSION for building against a minor 7 version
* Marks php5.6 as legacy

#### How should this be manually tested?

* `make php`
* Check php versions in each image

#### Any background context you want to provide?

N/A

#### What are the relevant tickets?

N/A

##### Does any external documentation require updating?

N/A

##### Does this changeset require specific versions of supporting software?
(i.e. Go / Terraform / Docker)

N/A

### CODE REVIEW

**Comment by kimpepper** [comment]
Looks great!. 

Do we need to call it `Makefile.php`? I can see editors having problems, and people being confused. Maybe `Makefile-php`?

**Comment by nickschuch** [comment]
Great idea!!!

**Comment by kimpepper** [comment]
LGTM! 👍

**Comment by kimpepper** [comment]
Closed in favour of #51

**Pull request closed without merging**
