### PR TITLE
add libfontconfig for PhantomJS

### PR DESCRIPTION
**Pull request by joshuataylor**

### CODE REVIEW

**Comment by nickschuch** [comment]
What are your thoughts on running this in a separate container and using linking?

**Comment by nickschuch** [comment]
Having PhantomJS in a container + linked also solves the problem where I see developers wgetting phantomjs in code. That should save some time + make sure PhantomJS is running before tests kick off.

**Comment by kimpepper** [comment]
Yeah, I agree. I like to think of containers as 'processes' rather than 'vms'.

**Comment by joshuataylor** [comment]
Also agreed.

**Pull request closed without merging**
